### ISSUE TITLE
For Nest integration user: do not update to 3.12.4

### ISSUE THREAD

**Issue by Nardol** [pascallj/python3.12-backport#2]
I know it is not really the matter of this repository but Python 3.12.3 should not be removed from the repository as long as possible because of home-assistant/core#119223
Nest users should not update Python.

**Comment by pascallj** [comment]
Thanks for letting me know. I usually keep two versions on the repository so we're still good for now. However people will have to hold these packages back manually. 

Although the main motivation of this repository is for Home Assistant, this repository serves a bigger purpose and I'm not going to solve issues from other packages.

If you could keep this issue up-to-date with important changes, that would be great!

**Comment by Nardol** [comment]
Sure, I have bookmarked this issue. For the moment I have set this pining:

```
Package: python3.12 libpython3.12-minimal python3.12-venv libpython3.12 libpython3.12-dev python3.12-dev python3.12-minimal libpython3.12-stdlib
Pin: version 3.12.3-1~bpo12+1 
Pin-Priority: 999
```

But I follow the referenced issue and will post here in case of changes.

Should I also post in the [community guide](https://community.home-assistant.io/t/python-3-12-backport-for-debian-12-bookworm/709459?u=nardol)?

EDIT: I've posted to give more detailed instructions.

**Comment by pascallj** [comment]
Personally, I think a better way hold back the packages is by using apt-mark. This is a less permanent solution and will remind you every time you upgrade, that some packages have been held back and you might check again if it's safe to upgrade.

To do this, install the 3.12.3-1~bpo12+1 version:

```bash
sudo apt install python3.12=3.12.3-1~bpo12+1 libpython3.12-minimal=3.12.3-1~bpo12+1 python3.12-venv=3.12.3-1~bpo12+1 libpython3.12=3.12.3-1~bpo12+1 libpython3.12-dev=3.12.3-1~bpo12+1 python3.12-dev=3.12.3-1~bpo12+1 python3.12-minimal=3.12.3-1~bpo12+1 libpython3.12-stdlib=3.12.3-1~bpo12+1
```

and afterwards mark all these package on hold:

```bash
sudo apt-mark hold python3.12 libpython3.12-minimal python3.12-venv libpython3.12 libpython3.12-dev python3.12-dev python3.12-minimal libpython3.12-stdlib
```

**Comment by Nardol** [comment]
As stated in https://github.com/home-assistant/core/issues/119223#issuecomment-2197031502 upgrading Mashumaro to the latest version make Nest integration working with Python 3.12.4.
`pip install --upgrade mashumaro`\ in the virtual env where HA core is running solve the issue".
