### ISSUE TITLE
Latest release breaks Home Assistant

### ISSUE THREAD

**Issue by autostatic** [pascallj/python3.12-backport#3]
Hello,

After having updated to Python 3.12.7-3~bpo12+1 on my Raspberry Pi with Raspberry Pi OS Bookworm Home Assistant refuses to start:
```
Nov 28 18:05:34 raspberrypi systemd[1]: Started homeassistant.service - Home Assistant.
Nov 28 18:05:34 raspberrypi hass[72758]: Traceback (most recent call last):
Nov 28 18:05:34 raspberrypi hass[72758]:   File "/mnt/data/homeassistant/bin/hass", line 8, in <module>
Nov 28 18:05:34 raspberrypi hass[72758]:     sys.exit(main())
Nov 28 18:05:34 raspberrypi hass[72758]:              ^^^^^^
Nov 28 18:05:34 raspberrypi hass[72758]:   File "/mnt/data/homeassistant/lib/python3.12/site-packages/homeassistant/__main__.py", line 173, in main
Nov 28 18:05:34 raspberrypi hass[72758]:     args = get_arguments()
Nov 28 18:05:34 raspberrypi hass[72758]:            ^^^^^^^^^^^^^^^
Nov 28 18:05:34 raspberrypi hass[72758]:   File "/mnt/data/homeassistant/lib/python3.12/site-packages/homeassistant/__main__.py", line 83, in get_arguments
Nov 28 18:05:34 raspberrypi hass[72758]:     from . import config as config_util
Nov 28 18:05:34 raspberrypi hass[72758]:   File "/mnt/data/homeassistant/lib/python3.12/site-packages/homeassistant/config.py", line 27, in <module>
Nov 28 18:05:34 raspberrypi hass[72758]:     from . import auth
Nov 28 18:05:34 raspberrypi hass[72758]:   File "/mnt/data/homeassistant/lib/python3.12/site-packages/homeassistant/auth/__init__.py", line 15, in <module>
Nov 28 18:05:34 raspberrypi hass[72758]:     from homeassistant import data_entry_flow
Nov 28 18:05:34 raspberrypi hass[72758]:   File "/mnt/data/homeassistant/lib/python3.12/site-packages/homeassistant/data_entry_flow.py", line 21, in <module>
Nov 28 18:05:34 raspberrypi hass[72758]:     from .core import HomeAssistant, callback
Nov 28 18:05:34 raspberrypi hass[72758]:   File "/mnt/data/homeassistant/lib/python3.12/site-packages/homeassistant/core.py", line 109, in <module>
Nov 28 18:05:34 raspberrypi hass[72758]:     from .util.executor import InterruptibleThreadPoolExecutor
Nov 28 18:05:34 raspberrypi hass[72758]:   File "/mnt/data/homeassistant/lib/python3.12/site-packages/homeassistant/util/executor.py", line 14, in <module>
Nov 28 18:05:34 raspberrypi hass[72758]:     from .thread import async_raise
Nov 28 18:05:34 raspberrypi hass[72758]:   File "/mnt/data/homeassistant/lib/python3.12/site-packages/homeassistant/util/thread.py", line 3, in <module>
Nov 28 18:05:34 raspberrypi hass[72758]:     import ctypes
Nov 28 18:05:34 raspberrypi hass[72758]:   File "/usr/lib/python3.12/ctypes/__init__.py", line 157, in <module>
Nov 28 18:05:34 raspberrypi hass[72758]:     class py_object(_SimpleCData):
Nov 28 18:05:34 raspberrypi hass[72758]: AttributeError: class must define a '_type_' attribute
Nov 28 18:05:34 raspberrypi systemd[1]: homeassistant.service: Main process exited, code=exited, status=1/FAILURE
```

Also tried updating Home Assistant to the latest version to no avail. After reverting to Python 3.12.6-1~bpo12+1 Home Assistant started working again. Anybody else having this issue?

Jeremy

**Comment by pascallj** [comment]
Hi Jeremy,

I'm sorry you're having issues. What Raspberry Pi are you using? I just spun up a fresh quick x86 instance and that one is fine. Is this directly on start or after performing a specific action?

**Comment by autostatic** [comment]
Raspberry Pi 5. This happens directly on start.

**Comment by pascallj** [comment]
I'm sorry I can't reproduce this. I tried a fresh Home Assistant installation on ARM64 (which is the same as the RPI 5) with 3.12.6-1\~bpo12+1 and then upgraded to 3.12.7-3\~bpo12+1 and had no issues. According to the stacktrace, the fault should occur as soon as the `auth` integration is loaded, which should be the login screen. I had no issues creating an account and logging in on my instance.

Are you sure you haven't experimented with different packages or Python virtual environments recently?

I recommended you try to recreate you virtual environment and see if that solves your issue:
* Stop Home Assistant via systemd
* Rename the old venv directory
* Create a new venv directory with the same name as the old one
* Create a new venv in this directory. In the new venv, first install `wheel`, then `homeassistant` and `numpy`.
* Start Home Assistant via systemd

If that doesn't fix this issue, temporarily move your homeassistant data directory out of the way and try with a fresh installation and see if that solves the issue.

**Comment by autostatic** [comment]
Ah, thanks for that advise, starting with a clean virtual environment seems to do the trick! Many thanks for the quick response. If I run into this issue again I will also recreate a fresh virtual env.

Jeremy

**Comment by pascallj** [comment]
I'm glad to hear that! No worries!

Normally this should only be needed on major upgrades (3.12 -> 3.13 e.g.), but I'm not sure what caused the issue now. Shouldn't be necessary every time. Let me know if you need to do this again on the next upgrade, because then there must be something wrong.
